name: CI/CD Pipeline for HealthConnect Front

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Frontend to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          cd /var/www/HealthConnect/healthconnect-frontend
          git pull
          docker build -t healthconnect-frontend:${{ github.sha }} .
          docker stop frontend || true
          docker rm frontend || true
          docker run -d --name frontend -p 8080:80 healthconnect-frontend:${{ github.sha }}
