name: CI/CD Pipeline for HealthConnect Front

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Deploy to server
    #   run: |
    #     ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "docker pull yourusername/healthconnect-frontend:latest && docker run -d -p 80:80 yourusername/healthconnect-frontend:latest"
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    #   shell: bash
